spring.application.name=classeo

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CLASSEO;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=QuidNovice

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.sql=debug

spring.jpa.open-in-view=false