spring.application.name=classeo

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CLASSEO;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=admin


#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.sql=debug

spring.jpa.open-in-view=false

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yQ2xhc3Nlb0Rldg==
jwt.expiration=3600000